CREATE DATABASE pros_db;
USE pros_db;


CREATE TABLE users(
    username VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    userAppName VARCHAR(100) NOT NULL,
    profilePhoto VARCHAR(100) NOT NULL,
    userType VARCHAR(45) NOT NULL,
    PRIMARY KEY(username)
);

CREATE TABLE hostelleave(
name VARCHAR(100) NOT NULL,
phno INT(11) NOT NULL,
emailID VARCHAR(200) NOT NULL,
year INT(4) NOT NULL,
reason VARCHAR(400) NOT NULL,
dep VARCHAR(100) NOT NULL,
fdate VARCHAR(12) NOT NULL,
tdate VARCHAR(12) NOT NULL,
letter VARCHAR(500) NOT NULL,
decision VARCHAR(5),
PRIMARY KEY(name)
);

CREATE TABLE earlyleave(
name VARCHAR(100) NOT NULL,
phno INT(11) NOT NULL,
emailID VARCHAR(200) NOT NULL,
year INT(4) NOT NULL,
reason VARCHAR(400) NOT NULL,
dep VARCHAR(100) NOT NULL,
tdate VARCHAR(12) NOT NULL,
time VARCHAR(12) NOT NULL,
letter VARCHAR(500) NOT NULL,
decision VARCHAR(5),
PRIMARY KEY(name)
);

CREATE TABLE onduty(
name VARCHAR(100) NOT NULL,
phno INT(11) NOT NULL,
emailID VARCHAR(200) NOT NULL,
year INT(4) NOT NULL,
reason VARCHAR(400) NOT NULL,
dep VARCHAR(100) NOT NULL,
tdate VARCHAR(12) NOT NULL,
ftime VARCHAR(12) NOT NULL,
ttime VARCHAR(12) NOT NULL,
letter VARCHAR(500) NOT NULL,
decision VARCHAR(5),
PRIMARY KEY(name)
);

CREATE TABLE reqdoc(
name VARCHAR(100) NOT NULL,
phno INT(11) NOT NULL,
emailID VARCHAR(200) NOT NULL,
year INT(4) NOT NULL,
reason VARCHAR(400) NOT NULL,
dep VARCHAR(100) NOT NULL,
tdate VARCHAR(12) NOT NULL,
time VARCHAR(12) NOT NULL,
letter VARCHAR(500) NOT NULL,
decision VARCHAR(5),
PRIMARY KEY(name)
);


CREATE TABLE otherreq(
name VARCHAR(100) NOT NULL,
phno INT(11) NOT NULL,
emailID VARCHAR(200) NOT NULL,
year INT(4) NOT NULL,
reason VARCHAR(400) NOT NULL,
dep VARCHAR(100) NOT NULL,
femail VARCHAR(200) NOT NULL,
letter VARCHAR(500) NOT NULL,
decision VARCHAR(5),
PRIMARY KEY(name)
);